### ISSUE TITLE
Adding a cacheKey attribute to a DOM element causes a React dev warning.

### ISSUE THREAD

**Issue by aickin** [FormidableLabs/rapscallion#49]
`ReactDOM.render` checks properties on DOM elements to make sure they are valid HTML attributes, and it throws a console warning in development mode if not. Since `cacheKey` is not a valid HTML attribute, rendering `<div cacheKey="foo"/>` results in this console warning:

```
Warning: Unknown prop `cacheKey` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

I would suggest changing the name of the prop to `data-cacheKey` or `data-cache-key`. That will avoid the unknown prop warning.

**Comment by divmain** [comment]
I've had a fix for this in mind, and probably should have included it before the public launch.  I do have a [potential fix](https://github.com/FormidableLabs/rapscallion/commit/76f2d653ab30c60acc448f1f46f6317649bf6933) for this in another branch.

On the one hand, I like the idea of changing to use a `data-*` attr for this, since that would be more in-line with typical React patterns.  On the other hand, it's probably better for the cache keys to stay out of the DOM altogether, since they might be large and there's no reason to inject them on the client side.

That's why I was thinking a simple Babel transform to strip the `cacheKey` attrs.  Then again, there's nothing saying it couldn't strip `data-cacheKey` either.  Thoughts @aweary @kenwheeler?

**Comment by montogeek** [comment]
I like `data-cacheKey`, `data` attributes were created for extensibility, this a good use case

**Comment by aweary** [comment]
I think the `cacheKey` should be stripped. It serves no purpose on the client and will just increase response size.
